import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { GitBranch, Plus } from "lucide-react";
import { RequireUser } from "@/lib/auth/gates";
import { createDiscovery, listDiscoveries, listRepositories } from "@/lib/gate/api";
import { useAsync } from "@/lib/use-async";
import { Page, Card, CardHeader, Empty } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input, Select, Textarea } from "@/components/ui/input";
import { Status, Hash } from "@/components/status";
export const Route = createFileRoute("/discoveries")({ component: () => <RequireUser><Discoveries /></RequireUser> });
function Discoveries() {
  const commits=useAsync(()=>listDiscoveries()); const repos=useAsync(()=>listRepositories()); const [open,setOpen]=useState(false); const [repo,setRepo]=useState(""); const [parent,setParent]=useState(""); const [branch,setBranch]=useState("main"); const [title,setTitle]=useState(""); const [claim,setClaim]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await createDiscovery({data:{repositoryId:repo||repos.data?.[0]?.id,parentId:parent||undefined,branch,title,claim,evidenceRefs:[]}});setTitle("");setClaim("");setParent("");setOpen(false);await commits.reload();}catch(e){setError(e instanceof Error?e.message:"Failed");}finally{setBusy(false);}}
  return <Page eyebrow="Git for AI discovery" title="Discoveries" description="Version claims and machine-generated findings as immutable commits. Failed branches stay visible; trusted findings retain exact lineage instead of collapsing into a final report." actions={<Button onClick={()=>setOpen(!open)}><Plus className="size-4"/>New discovery commit</Button>}>
    {(error||commits.error)&&<div className="mb-4 rounded-lg border border-red-800/40 bg-red-500/10 p-3 text-sm text-red-300">{error||commits.error}</div>}
    {open&&<Card className="mb-6"><CardHeader title="Commit a proposed finding"><p className="mt-1 text-xs text-muted">A commit is a proposal, not a trusted discovery. Promotion should be gated by evidence and verification.</p></CardHeader><form onSubmit={submit} className="grid gap-3 p-4 md:grid-cols-2"><label className="space-y-1"><span className="text-xs text-muted">Repository</span><Select value={repo||repos.data?.[0]?.id||""} onChange={e=>setRepo(e.target.value)}>{repos.data?.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label><label className="space-y-1"><span className="text-xs text-muted">Branch</span><Input value={branch} onChange={e=>setBranch(e.target.value)} required/></label><label className="space-y-1"><span className="text-xs text-muted">Parent commit (optional)</span><Select value={parent} onChange={e=>setParent(e.target.value)}><option value="">No parent</option>{commits.data?.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</Select></label><label className="space-y-1"><span className="text-xs text-muted">Title</span><Input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Model X improves held-out accuracy"/></label><label className="space-y-1 md:col-span-2"><span className="text-xs text-muted">Claim</span><Textarea value={claim} onChange={e=>setClaim(e.target.value)} required placeholder="State the bounded claim precisely enough that another agent or human can try to falsify it."/></label><div className="md:col-span-2"><Button disabled={busy}>{busy?"Committing…":"Create immutable commit"}</Button></div></form></Card>}
    {commits.data?.length?<div className="space-y-3">{commits.data.map((c:any)=><Card key={c.id} className="p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-subtle"><GitBranch className="size-3"/>{c.repository_name} / {c.branch}</div><h2 className="mt-2 text-base font-semibold">{c.title}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">{c.claim}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-subtle"><Hash value={c.content_hash} chars={16}/>{c.parent_id&&<span>parent <Hash value={c.parent_id} chars={8}/></span>}</div></div><Status value={c.status}/></div></Card>)}</div>:<Empty title="No discovery commits" text="When AI generates a claim worth remembering, commit the claim, evidence references, and parent lineage instead of burying it in a transcript."/>}
  </Page>;
}
