import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, LockKeyhole, Plus, ShieldAlert } from "lucide-react";
import { RequireUser } from "@/lib/auth/gates";
import { CAPABILITIES, type Capability, type EvidenceKind } from "@/lib/gate/types";
import { APPROVAL_PHRASE, recommendPolicyPack } from "@/lib/gate/policy";
import { createCandidate, getCandidate, listCandidates, listRepositories, proposeAdversarialChecks, recordEvidence, decideRelease } from "@/lib/gate/api";
import { useAsync } from "@/lib/use-async";
import { Page, Card, CardHeader, Empty } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input, Select, Textarea } from "@/components/ui/input";
import { ComponentChanges, EvidenceAssessments } from "@/components/change-evidence";
import { Status, Hash } from "@/components/status";
export const Route = createFileRoute("/gates")({ component: () => <RequireUser><Gates /></RequireUser> });

function Gates() {
  const candidates = useAsync(() => listCandidates({ data: {} }));
  const repos = useAsync(() => listRepositories());
  const [showNew,setShowNew]=useState(false); const [selected,setSelected]=useState<string|null>(null);
  return <Page eyebrow="Semantic change control" title="Gates" description="Freeze an exact AI artifact. HodgeForm compiles capability changes into evidence obligations and refuses release until the frozen policy is satisfied." actions={<Button onClick={()=>setShowNew(!showNew)}><Plus className="size-4"/>New candidate</Button>}>
    {showNew && <NewCandidate repos={repos.data ?? []} onCreated={async(id)=>{setShowNew(false); setSelected(id); await candidates.reload();}}/>}
    {candidates.error && <ErrorBox text={candidates.error}/>} 
    <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
      <Card><CardHeader title="Release candidates" meta={<span className="text-xs text-muted">{candidates.data?.length ?? 0}</span>}/><div className="max-h-[72dvh] divide-y divide-border overflow-y-auto">{candidates.data?.length ? candidates.data.map((c:any)=><button key={c.id} onClick={()=>setSelected(c.id)} className={`flex w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-bg-subtle ${selected===c.id?"bg-bg-subtle":""}`}><div className="min-w-0"><div className="truncate text-sm font-medium">{c.repository_name} · {c.version}</div><div className="mt-1 flex items-center gap-2"><Hash value={c.artifact_hash}/><span className="text-[11px] text-muted">{c.risk}</span></div></div><div className="flex items-center gap-2"><Status value={c.status}/><ChevronRight className="size-3 text-subtle"/></div></button>) : <div className="p-4"><Empty title="No frozen candidates" text="Create an exact artifact candidate and HodgeForm will compile its release obligations."/></div>}</div></Card>
      {selected ? <CandidateInspector candidateId={selected} onChanged={candidates.reload}/> : <Card className="grid min-h-96 place-items-center p-8"><div className="max-w-md text-center"><LockKeyhole className="mx-auto size-8 text-subtle"/><h2 className="mt-4 text-lg font-semibold">Select a gate</h2><p className="mt-2 text-sm leading-6 text-muted">Inspect the immutable policy lock, semantic capability diff, admissible evidence, and release decision.</p></div></Card>}
    </div>
  </Page>;
}

function NewCandidate({ repos, onCreated }: { repos:any[]; onCreated:(id:string)=>Promise<void> }) {
  const [components,setComponents]=useState("[]");
  const [repoId,setRepoId]=useState(repos[0]?.id??""); const [version,setVersion]=useState("v1"); const [name,setName]=useState("Customer support agent"); const [framework,setFramework]=useState("MCP / custom"); const [hash,setHash]=useState(""); const [pack,setPack]=useState("auto"); const [dataClass,setDataClass]=useState("internal"); const [caps,setCaps]=useState<Capability[]>(["network.outbound"]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{ if(!repoId&&repos[0]?.id)setRepoId(repos[0].id); },[repos,repoId]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const recommended=recommendPolicyPack(caps);const resolvedPack=pack==="auto"?recommended:pack;const result=await createCandidate({data:{repositoryId:repoId,version,artifactHash:hash,manifest:{name,framework,capabilities:caps,components:JSON.parse(components)},intent:{pack:resolvedPack as any,dataClass:dataClass as any}}});await onCreated(result.candidateId);}catch(e){setError(e instanceof Error?e.message:"Failed to freeze candidate");}finally{setBusy(false);}}
  if(!repos.length) return <Card className="mb-6 p-5"><p className="text-sm text-muted">Create a repository before freezing a release candidate.</p></Card>;
  return <Card className="mb-6"><CardHeader title="Freeze release candidate"><p className="mt-1 text-xs text-muted">The gate policy is compiled server-side once and content-hashed before evidence collection starts.</p></CardHeader><form onSubmit={submit} className="grid gap-4 p-4 lg:grid-cols-2">
    <label className="space-y-1"><span className="text-xs text-muted">Repository</span><Select value={repoId} onChange={e=>setRepoId(e.target.value)}>{repos.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label>
    <label className="space-y-1"><span className="text-xs text-muted">Version</span><Input value={version} onChange={e=>setVersion(e.target.value)} required/></label>
    <label className="space-y-1"><span className="text-xs text-muted">Agent name</span><Input value={name} onChange={e=>setName(e.target.value)} required/></label>
    <label className="space-y-1"><span className="text-xs text-muted">Framework</span><Input value={framework} onChange={e=>setFramework(e.target.value)}/></label>
    <label className="space-y-1"><span className="text-xs text-muted">Policy pack</span><Select value={pack} onChange={e=>setPack(e.target.value)}><option value="auto">Auto (recommended from authority)</option><option value="basic">Basic</option><option value="networked">Networked agent</option><option value="code-execution">Code execution</option><option value="action-taking">Action taking</option><option value="high-risk">High risk</option></Select></label>
    <label className="space-y-1"><span className="text-xs text-muted">Data class</span><Select value={dataClass} onChange={e=>setDataClass(e.target.value)}><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="regulated">Regulated</option></Select></label>
    <div className="lg:col-span-2"><div className="mb-2 text-xs text-muted">Capabilities</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{CAPABILITIES.map(cap=><label key={cap} className="flex items-center gap-2 rounded-lg border border-border bg-bg px-3 py-2 text-xs"><input type="checkbox" checked={caps.includes(cap)} onChange={e=>setCaps(e.target.checked?[...caps,cap]:caps.filter(c=>c!==cap))}/><span className="font-mono">{cap}</span></label>)}</div></div>
    <div className="lg:col-span-2"><div className="mb-1 flex items-center justify-between"><span className="text-xs text-muted">Artifact SHA-256</span><span className="text-[11px] text-subtle">Use <code>hodgeform hash &lt;artifact&gt;</code> or CLI submit</span></div><Input value={hash} onChange={e=>setHash(e.target.value.trim())} pattern="[a-fA-F0-9]{64}" required placeholder="64-hex SHA-256 of the exact artifact/bundle bytes"/><p className="mt-1 text-[11px] text-muted">HodgeForm never invents this value. The release candidate is bound to the exact digest you supply.</p></div>
    <details className="lg:col-span-2"><summary className="cursor-pointer text-sm">Versioned components (optional)</summary><p className="my-2 text-xs text-muted">Provide a JSON array of components: id, kind (prompt, tool, policy, verifier, memory, world_model, representation), digest (SHA-256), and contract. Changes create additional evidence obligations.</p><Textarea aria-label="Versioned component contracts" value={components} onChange={e=>setComponents(e.target.value)} className="font-mono text-xs"/></details>
    {error&&<div className="lg:col-span-2"><ErrorBox text={error}/></div>}<div className="lg:col-span-2"><Button disabled={busy}>{busy?"Freezing…":"Compile & freeze gate"}</Button></div>
  </form></Card>;
}

function CandidateInspector({ candidateId, onChanged }: { candidateId:string; onChanged:()=>Promise<void> }) {
  const details=useAsync(()=>getCandidate({data:{candidateId}}),[candidateId]);
  const [requirementId,setRequirementId]=useState(""); const [kind,setKind]=useState<EvidenceKind>("deterministic_test"); const [outcome,setOutcome]=useState("pass"); const [source,setSource]=useState("ci.verifier"); const [payload,setPayload]=useState('{"note":"Attach exact test output, digest, or verifier result here."}'); const [confirmation,setConfirmation]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [redTeam,setRedTeam]=useState<any>(null);
  const firstMissing=useMemo(()=>details.data?.verdicts?.find((v:any)=>v.status!=="pass")?.requirement?.id??details.data?.verdicts?.[0]?.requirement?.id??"",[details.data]);
  useEffect(()=>{setRequirementId(firstMissing)},[firstMissing]);
  const requirement=details.data?.verdicts?.find((v:any)=>v.requirement.id===requirementId)?.requirement;
  const manuallyRecordableKinds=(requirement?.allowedEvidence??[]).filter((k:EvidenceKind)=>!["independent_verifier","formal_proof","human_approval"].includes(k));
  const selectedKind=manuallyRecordableKinds.includes(kind)?kind:(manuallyRecordableKinds[0]??"deterministic_test");
  async function suggestTests(){setBusy(true);setError("");try{setRedTeam(await proposeAdversarialChecks({data:{candidateId}}));}catch(e){setError(e instanceof Error?e.message:"Unable to generate red-team suggestions");}finally{setBusy(false);}}
  async function addEvidence(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await recordEvidence({data:{candidateId,requirementId,evidenceKind:selectedKind,outcome:outcome as any,source,payload:JSON.parse(payload||"{}")}});await details.reload();await onChanged();}catch(e){setError(e instanceof Error?e.message:"Failed to record evidence");}finally{setBusy(false);}}
  async function decide(){setBusy(true);setError("");try{await decideRelease({data:{candidateId,expectedPolicyHash:details.data!.plan.policy_hash,confirmation}});setConfirmation("");await details.reload();await onChanged();}catch(e){setError(e instanceof Error?e.message:"Decision failed");}finally{setBusy(false);}}
  if(details.loading||!details.data)return <Card className="p-6 text-sm text-muted">Loading frozen gate…</Card>;
  if(details.error)return <ErrorBox text={details.error}/>;
  const d:any=details.data; const p=d.plan.compiled_policy_json;
  return <div className="space-y-4">
    <Card><div className="flex items-start justify-between gap-4 p-4"><div><div className="font-mono text-[10px] uppercase tracking-[.13em] text-subtle">Optional local red team</div><p className="mt-2 text-sm text-muted">Ask the configured local model to propose falsification tests against this exact frozen policy. Suggestions are never release authority.</p></div><Button variant="secondary" size="sm" onClick={()=>void suggestTests()} disabled={busy}>Propose tests</Button></div>{redTeam&&<div className="border-t border-border p-4"><div className="mb-3 text-xs text-muted">{redTeam.model} · {redTeam.provider} · policy <Hash value={redTeam.policyHash}/></div><div className="space-y-2">{(redTeam.tests??[]).map((t:any,i:number)=><div key={i} className="rounded-lg border border-border bg-bg p-3"><div className="text-xs font-medium">{t.requirementId??"Unmapped"} · {t.title??"Adversarial test"}</div><p className="mt-1 text-xs leading-5 text-muted">{t.testIdea??JSON.stringify(t)}</p>{t.failureSignal&&<p className="mt-1 text-[11px] text-red-300">Failure signal: {t.failureSignal}</p>}</div>)}</div></div>}</Card>
    <Card><CardHeader title={`${d.candidate.manifest_json.name} · ${d.candidate.version}`} meta={<Status value={d.candidate.status}/>}/><div className="grid gap-4 p-4 md:grid-cols-3"><Metric label="Artifact" value={<Hash value={d.candidate.artifact_hash} chars={16}/>}/><Metric label="Frozen policy" value={<Hash value={d.plan.policy_hash} chars={16}/>}/><Metric label="Risk" value={<span className="capitalize">{d.candidate.risk}</span>}/></div>{p.addedCapabilities?.length>0&&<div className="border-t border-border bg-amber-500/5 px-4 py-3"><div className="flex items-center gap-2 text-xs font-medium text-amber-300"><ShieldAlert className="size-4"/>Semantic authority expanded</div><div className="mt-2 flex flex-wrap gap-2">{p.addedCapabilities.map((c:string)=><code key={c} className="rounded bg-bg px-2 py-1 font-mono text-[11px] text-amber-200">+ {c}</code>)}</div></div>}</Card>
    {d.experiments?.length>0&&<Card><CardHeader title="Frozen experiment gates"/><div className="divide-y divide-border">{d.experiments.map((e:any)=><div key={e.id} className="p-4"><Status value={e.status}/><p className="mt-2 text-xs text-muted">{e.scope}</p><Hash value={e.experimentHash}/></div>)}</div></Card>}
    <ComponentChanges changes={d.candidate.semantic_diff_json.components ?? []}/>
    <Card><CardHeader title="Trust transition" meta={<span className="font-mono text-[10px] uppercase tracking-[.13em] text-accent">proof before trust</span>}/><div className="grid gap-px bg-border md:grid-cols-4"><TrustCell label="What changed"><div className="space-y-1">{d.trustTransition.changed.addedCapabilities.length?d.trustTransition.changed.addedCapabilities.map((c:string)=><code key={`a-${c}`} className="block font-mono text-[11px] text-amber-200">+ {c}</code>):<span className="text-xs text-muted">No added authority declared.</span>}{d.trustTransition.changed.removedCapabilities.map((c:string)=><code key={`r-${c}`} className="block font-mono text-[11px] text-emerald-200">− {c}</code>)}</div></TrustCell><TrustCell label="What must be proven"><div className="text-sm font-medium">{d.trustTransition.proof.totalObligations} blocking obligation(s)</div><p className="mt-1 text-xs leading-5 text-muted">{d.trustTransition.proof.semanticObligationIds.length?`${d.trustTransition.proof.semanticObligationIds.length} added by the authority change.`:"Frozen before evidence collection."}</p></TrustCell><TrustCell label="What evidence counts"><div className="text-sm font-medium">Typed + independence-aware</div><p className="mt-1 text-xs leading-5 text-muted">LLM PASS cannot satisfy a blocking obligation. Registered verifier identity determines independent evidence.</p></TrustCell><TrustCell label="Who can approve"><div className="text-sm font-medium">{d.trustTransition.approval.requiredRole==="owner-or-admin"?"Owner or admin":"Authorized workspace member"}</div><p className="mt-1 text-xs leading-5 text-muted">{d.trustTransition.approval.separateFromCreator?"Must be different from the candidate creator.":"Separation is not mandatory for this risk level."}</p></TrustCell></div></Card>
    <Card><CardHeader title="Compiled evidence obligations" meta={<span className="text-xs text-muted">{d.verdicts.filter((v:any)=>v.status==="pass").length}/{d.verdicts.length} satisfied</span>}/><div className="divide-y divide-border">{d.verdicts.map((v:any)=><div key={v.requirement.id} className="grid gap-2 px-4 py-3 md:grid-cols-[110px_1fr_auto] md:items-center"><div className="font-mono text-[11px] text-muted">{v.requirement.id}</div><div><div className="text-sm">{v.requirement.title}</div><div className="mt-1 text-xs leading-5 text-muted">{v.requirement.reason}</div><div className="mt-1 font-mono text-[10px] text-subtle">admissible: {v.requirement.allowedEvidence.join(", ")} · min independence: {v.requirement.minimumIndependence}</div><EvidenceAssessments assessments={v.assessments ?? []}/></div><Status value={v.status}/></div>)}</div></Card>
    {d.candidate.status==="frozen"&&<Card><CardHeader title="Attach evidence"><p className="mt-1 text-xs text-muted">Evidence is typed, scoped, hashed, and append-only. LLM PASS results never satisfy a blocking obligation alone.</p></CardHeader><form onSubmit={addEvidence} className="grid gap-3 p-4 md:grid-cols-2"><label className="space-y-1"><span className="text-xs text-muted">Requirement</span><Select value={requirementId} onChange={e=>setRequirementId(e.target.value)}>{d.verdicts.map((v:any)=><option key={v.requirement.id} value={v.requirement.id}>{v.requirement.id} · {v.requirement.title}</option>)}</Select></label><label className="space-y-1"><span className="text-xs text-muted">Evidence kind</span><Select value={manuallyRecordableKinds.length?selectedKind:""} onChange={e=>setKind(e.target.value as EvidenceKind)} disabled={!manuallyRecordableKinds.length}>{manuallyRecordableKinds.length?manuallyRecordableKinds.map((k:EvidenceKind)=><option key={k}>{k}</option>):<option value="">Registered verifier required</option>}</Select></label><label className="space-y-1"><span className="text-xs text-muted">Outcome</span><Select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="pass">pass</option><option value="fail">fail</option><option value="inconclusive">inconclusive</option></Select></label><label className="space-y-1"><span className="text-xs text-muted">Verifier source</span><Input value={source} onChange={e=>setSource(e.target.value)} required/></label><label className="space-y-1 md:col-span-2"><span className="text-xs text-muted">Evidence payload (JSON)</span><Textarea value={payload} onChange={e=>setPayload(e.target.value)} className="font-mono text-xs"/></label><div className="md:col-span-2 space-y-2">{!manuallyRecordableKinds.length&&<p className="text-xs leading-5 text-amber-200">This obligation requires a registered verifier principal. Submit it with a verifier-bound API token; browser users cannot self-assert independence.</p>}<Button variant="secondary" disabled={busy||!manuallyRecordableKinds.length}>Record evidence receipt</Button></div></form></Card>}
    {d.evidence.length>0&&<Card><CardHeader title="Evidence ledger"/><div className="divide-y divide-border">{d.evidence.map((e:any)=><div key={e.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono text-[11px] text-muted">{e.requirement_id}</span><span className="text-xs">{e.evidence_kind}</span></div><div className="mt-1 text-[11px] text-subtle">{e.source} · {e.independence} · <Hash value={e.payload_hash}/></div></div><Status value={e.outcome}/></div>)}</div></Card>}
    {d.candidate.status==="frozen"&&<Card><CardHeader title="Request release decision"><p className="mt-1 text-xs text-muted">This freezes the evidence snapshot. Missing or failed obligations produce a signed BLOCK receipt; satisfied gates produce RELEASE.</p></CardHeader><div className="space-y-3 p-4"><div className={`rounded-lg border p-3 text-sm ${d.gateReady?"border-emerald-800/50 bg-emerald-500/5 text-emerald-200":"border-amber-800/50 bg-amber-500/5 text-amber-200"}`}>{d.gateReady?<span className="flex items-center gap-2"><CheckCircle2 className="size-4"/>All configured obligations currently satisfied.</span>:<span>One or more obligations or frozen experiments remain unsatisfied. Requesting a decision now will produce BLOCK.</span>}</div>{p.approval.separateFromCreator&&<div className="rounded-lg border border-border bg-bg p-3 text-xs text-muted">Four-eyes control is mandatory for {p.risk}-risk releases. The candidate creator cannot approve this gate.</div>}<Input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={APPROVAL_PHRASE}/>{error&&<ErrorBox text={error}/>}<Button onClick={()=>void decide()} disabled={busy||confirmation!==APPROVAL_PHRASE}>{busy?"Deciding…":"Sign release decision"}</Button></div></Card>}
    {d.receipt && d.receipt.receipt_json.evaluator!=="hodgeform-obligation-evaluator/2" && <ErrorBox text="Historical receipt: this decision predates obligation-isolation enforcement. Create and evaluate a new candidate before using it for deployment."/>}
    {d.receipt&&<Card><CardHeader title="Signed release receipt" meta={<Status value={d.receipt.verdict}/>}/><div className="grid gap-3 p-4 md:grid-cols-2"><Metric label="Receipt hash" value={<Hash value={d.receipt.receipt_hash} chars={20}/>}/><Metric label="Signer" value={<span>{d.receipt.signer_id}</span>}/><Metric label="Public-key fingerprint" value={<Hash value={d.receipt.public_key_fingerprint} chars={20}/>}/><Metric label="Boundary" value={<span className="text-xs text-muted">Exact configured gate only; never universal safety.</span>}/></div></Card>}
    {error&&<ErrorBox text={error}/>} 
  </div>;
}
function TrustCell({label,children}:{label:string;children:React.ReactNode}){return <div className="bg-bg-elevated p-4"><div className="font-mono text-[10px] uppercase tracking-[.13em] text-subtle">{label}</div><div className="mt-2">{children}</div></div>}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <div><div className="font-mono text-[10px] uppercase tracking-[.13em] text-subtle">{label}</div><div className="mt-1 text-sm">{value}</div></div>}
function ErrorBox({text}:{text:string}){return <div className="rounded-lg border border-red-800/40 bg-red-500/10 p-3 text-sm text-red-300">{text}</div>}
