import { WorkerPanel } from "@/components/worker-panel";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Users, Plus, UserPlus, CheckCircle2 } from "lucide-react";
import { RequireUser } from "@/lib/auth/gates";
import { createWorkspace, inviteWorkspaceMember, listWorkspaceMembers, listWorkspaces, removeWorkspaceMember, setWorkspaceMemberRole, switchWorkspace } from "@/lib/gate/api";
import { useAsync } from "@/lib/use-async";
import { Page, Card, CardHeader, Empty } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/input";
export const Route=createFileRoute("/workspace")({component:()=> <RequireUser><Workspace/></RequireUser>});
function Workspace(){
 const ws=useAsync(()=>listWorkspaces()); const members=useAsync(()=>listWorkspaceMembers()); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [role,setRole]=useState<"member"|"admin">("member"); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
 async function make(){setError("");try{await createWorkspace({data:{name}} as never);setName("");await ws.reload();await members.reload();}catch(e){setError(e instanceof Error?e.message:"Unable to create workspace")}}
 async function change(id:string){setError("");try{await switchWorkspace({data:{workspaceId:id}} as never);await ws.reload();await members.reload();window.location.href="/";}catch(e){setError(e instanceof Error?e.message:"Unable to switch workspace")}}
 async function invite(){setError("");setNotice("");try{const r:any=await inviteWorkspaceMember({data:{email,role}} as never);setNotice(`Invitation created for ${r.email}. ${r.url?`Invite link: ${r.url}`:""}`);setEmail("");}catch(e){setError(e instanceof Error?e.message:"Unable to invite member")}}
 async function changeRole(userId:string,next:"owner"|"admin"|"member"){setError("");try{await setWorkspaceMemberRole({data:{userId,role:next}} as never);await members.reload();await ws.reload();}catch(e){setError(e instanceof Error?e.message:"Unable to change role")}}
 async function remove(userId:string){setError("");try{await removeWorkspaceMember({data:{userId}} as never);await members.reload();await ws.reload();}catch(e){setError(e instanceof Error?e.message:"Unable to remove member")}}
 return <Page eyebrow="Team boundary" title="Workspace" description="Repositories, evidence, API tokens and release decisions are workspace-scoped. High-risk gates can require a different workspace member to approve the exact frozen candidate.">
  {error&&<div className="mb-4 rounded-lg border border-red-800/40 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}{notice&&<div className="mb-4 rounded-lg border border-emerald-800/40 bg-emerald-500/10 p-3 text-sm text-emerald-300 break-all">{notice}</div>}
  <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader title="Your workspaces" meta={<Users className="size-4 text-subtle"/>}/><div className="divide-y divide-border">{ws.data?.map((w:any)=><div key={w.id} className="flex items-center justify-between gap-3 p-4"><div><div className="flex items-center gap-2 text-sm font-medium">{w.name}{w.active&&<CheckCircle2 className="size-3 text-emerald-300"/>}</div><div className="mt-1 text-xs text-muted">{w.role} · {w.slug}</div></div>{!w.active&&<Button variant="secondary" size="sm" onClick={()=>void change(w.id)}>Switch</Button>}</div>)}</div><div className="border-t border-border p-4"><div className="flex gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="New workspace name"/><Button onClick={()=>void make()} disabled={!name.trim()}><Plus className="size-3"/>Create</Button></div></div></Card>
  <Card><CardHeader title="Members" meta={<UserPlus className="size-4 text-subtle"/>}/>{members.data?.length?<div className="divide-y divide-border">{members.data.map((m:any)=>{const owner=ws.data?.find((w:any)=>w.active)?.role==="owner";return <div key={m.user_id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><div className="truncate text-sm font-medium">{m.name}</div><div className="truncate text-xs text-muted">{m.email}</div></div>{owner?<div className="flex items-center gap-2"><Select value={m.role} onChange={e=>void changeRole(m.user_id,e.target.value as any)}><option value="owner">Owner</option><option value="admin">Admin</option><option value="member">Member</option></Select><Button variant="secondary" size="sm" onClick={()=>void remove(m.user_id)}>Remove</Button></div>:<span className="font-mono text-[10px] uppercase text-subtle">{m.role}</span>}</div>})}</div>:<div className="p-4"><Empty title="No team members" text="Invite a second reviewer before using gates that require four-eyes approval."/></div>}<div className="border-t border-border p-4"><div className="grid gap-2 sm:grid-cols-[1fr_120px_auto]"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="reviewer@company.com"/><Select value={role} onChange={e=>setRole(e.target.value as any)}><option value="member">Member</option><option value="admin">Admin</option></Select><Button onClick={()=>void invite()} disabled={!email.trim()}>Invite</Button></div><p className="mt-2 text-xs text-muted">Invite tokens expire after seven days. If transactional email is configured, HodgeForm sends the link automatically.</p></div></Card></div>
 <WorkerPanel/>
 </Page>
}
