import assert from "node:assert/strict"; import test from "node:test"; import { generateKeyPairSync, createHash, sign } from "node:crypto"; import { mkdtemp, writeFile } from "node:fs/promises"; import { tmpdir } from "node:os"; import { join } from "node:path"; import { spawnSync } from "node:child_process";
function canonicalize(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalize).join(",")}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(v[k])}`).join(",")}}`;}
const sha=(x)=>createHash("sha256").update(x).digest("hex");
async function fixture(verdict="RELEASE") {const dir=await mkdtemp(join(tmpdir(),"hf-"));const {privateKey,publicKey}=generateKeyPairSync("ed25519");const payload={schema:"hodgeform-release-receipt/1",verdict,candidate:{artifactHash:"a".repeat(64)}};const canonical=canonicalize(payload);const pub=publicKey.export({type:"spki",format:"pem"}).toString();const fp=sha(publicKey.export({type:"spki",format:"der"}));const doc={schema:"hodgeform-signed-release/1",payload,receiptHash:sha(canonical),signerId:"test",signature:sign(null,Buffer.from(canonical),privateKey).toString("base64"),publicKeyFingerprint:fp};const rf=join(dir,"receipt.json"),pf=join(dir,"pub.pem");await writeFile(rf,JSON.stringify(doc));await writeFile(pf,pub);return{dir,rf,pf,doc};}
test("CLI accepts a valid RELEASE signed by the pinned key",async()=>{const f=await fixture();const r=spawnSync(process.execPath,["bin/hodgeform.mjs","receipt","verify",f.rf,"--public-key",f.pf],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/HodgeForm gate: RELEASE/);});
test("CLI rejects tampering and BLOCK receipts",async()=>{const f=await fixture();f.doc.payload.candidate.artifactHash="b".repeat(64);await writeFile(f.rf,JSON.stringify(f.doc));let r=spawnSync(process.execPath,["bin/hodgeform.mjs","receipt","verify",f.rf,"--public-key",f.pf],{encoding:"utf8"});assert.equal(r.status,2);assert.match(r.stderr,/Receipt hash mismatch/);const b=await fixture("BLOCK");r=spawnSync(process.execPath,["bin/hodgeform.mjs","receipt","verify",b.rf,"--public-key",b.pf],{encoding:"utf8"});assert.equal(r.status,3);});

test("CLI scanner detects consequential authority deterministically",async()=>{const dir=await mkdtemp(join(tmpdir(),"hf-scan-"));const src=join(dir,"agent.js");await writeFile(src,'import fs from "node:fs";\nfs.writeFileSync("/tmp/x","x");\nfetch("https://example.com");\n');const out=join(dir,"scan.json");const r=spawnSync(process.execPath,["bin/hodgeform.mjs","scan",src,"--out",out],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);const scan=JSON.parse(await (await import("node:fs/promises")).readFile(out,"utf8"));assert.equal(scan.complete,true);assert.ok(scan.detectedCapabilities.includes("filesystem.write"));assert.ok(scan.detectedCapabilities.includes("network.outbound"));});

test("CLI init defaults to auto policy selection",async()=>{const dir=await mkdtemp(join(tmpdir(),"hf-init-"));const r=spawnSync(process.execPath,[join(process.cwd(),"bin/hodgeform.mjs"),"init"],{cwd:dir,encoding:"utf8"});assert.equal(r.status,0,r.stderr);const config=JSON.parse(await (await import("node:fs/promises")).readFile(join(dir,"hodgeform.agent.json"),"utf8"));assert.equal(config.policy.pack,"auto");assert.deepEqual(config.capabilities,[]);});

test("CLI scanner recommends the least appropriate standard pack deterministically",async()=>{const cases=[
  ['fetch("https://example.com")','networked'],
  ['require("fs").writeFileSync("/tmp/x","x")','code-execution'],
  ['chat.postMessage({channel:"x",text:"y"})','action-taking'],
  ['stripe.paymentIntents.create({amount:100})','high-risk'],
  ['console.log("hello")','basic'],
];for(const [source,expected] of cases){const dir=await mkdtemp(join(tmpdir(),"hf-rec-"));const src=join(dir,"agent.js"),out=join(dir,"scan.json");await writeFile(src,source);const r=spawnSync(process.execPath,["bin/hodgeform.mjs","scan",src,"--out",out],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);const scan=JSON.parse(await (await import("node:fs/promises")).readFile(out,"utf8"));assert.equal(scan.recommendedPack,expected,`${source} -> ${scan.recommendedPack}`);}});

test("CLI capability scan is bound to the exact artifact digest",async()=>{const dir=await mkdtemp(join(tmpdir(),"hf-bind-"));const src=join(dir,"agent.js"),out=join(dir,"scan.json");await writeFile(src,'fetch("https://example.com")\n');let r=spawnSync(process.execPath,["bin/hodgeform.mjs","scan",src,"--out",out],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);const scan=JSON.parse(await (await import("node:fs/promises")).readFile(out,"utf8"));r=spawnSync(process.execPath,["bin/hodgeform.mjs","hash",src],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);assert.equal(scan.artifactHash,r.stdout.trim());});

test("server signing configuration rejects a mismatched Ed25519 keypair",async()=>{const cryptoServer=await import("../src/lib/gate/crypto.server.ts");const a=cryptoServer.generateReleaseKeys(),b=cryptoServer.generateReleaseKeys();const prevPriv=process.env.HODGEFORM_RECEIPT_PRIVATE_KEY_B64,prevPub=process.env.HODGEFORM_RECEIPT_PUBLIC_KEY_B64;try{process.env.HODGEFORM_RECEIPT_PRIVATE_KEY_B64=Buffer.from(a.privateKeyPem).toString("base64");process.env.HODGEFORM_RECEIPT_PUBLIC_KEY_B64=Buffer.from(b.publicKeyPem).toString("base64");assert.equal(cryptoServer.releaseKeyConfigured(),false);assert.throws(()=>cryptoServer.requireReleaseKeys(),/do not form a valid pair/);}finally{if(prevPriv===undefined)delete process.env.HODGEFORM_RECEIPT_PRIVATE_KEY_B64;else process.env.HODGEFORM_RECEIPT_PRIVATE_KEY_B64=prevPriv;if(prevPub===undefined)delete process.env.HODGEFORM_RECEIPT_PUBLIC_KEY_B64;else process.env.HODGEFORM_RECEIPT_PUBLIC_KEY_B64=prevPub;}});
