function esc(value: string) {
  return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}
function env(name: string, fallback = "") { return process.env[name]?.trim() || fallback; }
function shell(title: string, body: string) {
  const entity = esc(env("HODGEFORM_LEGAL_ENTITY_NAME", "HodgeForm"));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — HodgeForm</title><style>body{font:16px/1.55 system-ui,sans-serif;max-width:820px;margin:48px auto;padding:0 24px;color:#171717}h1,h2{line-height:1.2}a{color:inherit}code{background:#f4f4f4;padding:.1rem .3rem;border-radius:4px}.muted{color:#666}</style></head><body><p><a href="/">← HodgeForm</a></p><h1>${esc(title)}</h1><p class="muted">Operator: ${entity}. Effective date: ${esc(env("HODGEFORM_LEGAL_EFFECTIVE_DATE", "set by operator"))}.</p>${body}</body></html>`;
}
export function publicPage(path: string): string | null {
  const entity = esc(env("HODGEFORM_LEGAL_ENTITY_NAME", "HodgeForm"));
  const privacy = esc(env("HODGEFORM_PRIVACY_EMAIL", "privacy@example.invalid"));
  const support = esc(env("HODGEFORM_SUPPORT_EMAIL", "support@example.invalid"));
  const security = esc(env("HODGEFORM_SECURITY_EMAIL", "security@example.invalid"));
  const retention = esc(env("HODGEFORM_DATA_RETENTION_DAYS", "30"));
  if (path === "/privacy") return shell("Privacy Notice", `<p>${entity} operates HodgeForm, a release-assurance and evidence-management service for AI work.</p><h2>Data we process</h2><p>We process account identity, workspace membership, release candidates, policy/evidence metadata, API-token metadata, operational logs, and information you intentionally submit. HodgeForm is designed so source artifacts and model prompts need not be stored unless a configured feature explicitly requires them.</p><h2>Purpose</h2><p>We use data to authenticate users, isolate workspaces, operate release gates, preserve audit evidence, prevent abuse, support customers, secure the service, and meet contractual/legal obligations.</p><h2>Retention and deletion</h2><p>Default operational retention is ${retention} days unless a contract or required audit record specifies otherwise. Signed release receipts and audit evidence may have longer customer-configured retention because deleting them can destroy provenance. Account deletion removes Better Auth identity records after required workspace-ownership safeguards; tenant/business records follow the workspace/customer retention policy.</p><h2>Contact</h2><p>Privacy requests: <a href="mailto:${privacy}">${privacy}</a>. Support: <a href="mailto:${support}">${support}</a>.</p><p>This notice must be reviewed for the jurisdictions and contracts of the actual operator before public launch.</p>`);
  if (path === "/terms") return shell("Terms of Service", `<p>These terms govern access to HodgeForm operated by ${entity}. Do not use the service unless you are authorized to bind the relevant organization.</p><h2>Service boundary</h2><p>HodgeForm evaluates exact artifacts against configured release policies and evidence. A HodgeForm receipt is <strong>not</strong> a universal certificate of safety, correctness, regulatory compliance, causality, scientific validity, or fitness for a particular purpose.</p><h2>Customer responsibilities</h2><p>You are responsible for selecting appropriate policies, protecting credentials and signing trust roots, reviewing consequential releases, maintaining lawful rights to submitted data, and operating downstream systems safely. Do not use HodgeForm as the sole control for catastrophic or legally prohibited actions without independent safeguards appropriate to the risk.</p><h2>Acceptable use</h2><p>Do not attempt unauthorized access, cross-tenant access, service disruption, credential theft, malware distribution, or use that violates applicable law.</p><h2>Availability and changes</h2><p>Features and policies may evolve. Material changes to trust semantics should be versioned and auditable. Contractual SLAs, warranties, liability limits, governing law, payment terms, data-processing terms, and enterprise security obligations must be supplied by the operator's executed customer agreement.</p><h2>Contact</h2><p><a href="mailto:${support}">${support}</a></p><p>This page is an operational product template and must receive qualified legal review before open public launch.</p>`);
  if (path === "/security") return shell("Security & Vulnerability Disclosure", `<p>Report suspected vulnerabilities privately to <a href="mailto:${security}">${security}</a>.</p><h2>What to include</h2><p>Include affected endpoint/version, reproduction steps, impact, and any relevant request/receipt identifiers. Do not include unnecessary customer data.</p><h2>Research rules</h2><p>Use accounts and workspaces you control. Avoid privacy violations, destructive data access, denial of service, social engineering, or accessing another tenant's data. If you encounter sensitive data, stop and report it.</p><h2>Priority issues</h2><p>Tenant-boundary bypass, unauthorized release approval, receipt/signing-key compromise, API-token bypass, authentication/session bypass, and executor isolation escape are treated as high-priority security reports.</p><h2>Trust boundary</h2><p>Valid receipts attest that an exact configured gate was satisfied. They do not establish universal safety or compliance.</p>`);
  return null;
}
