/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1CandidatesRouteImport } from './routes/api/v1/candidates'
import { Route as ApiV1RepositoriesRouteImport } from './routes/api/v1/repositories'
import { Route as ApiV1VerifierJobsRouteImport } from './routes/api/v1/verifier-jobs'
import { Route as ApiV1CandidatesIdRouteImport } from './routes/api/v1/candidates/$id'
import { Route as ApiV1CandidatesIdEvidenceRouteImport } from './routes/api/v1/candidates/$id/evidence'
import { Route as ApiV1CandidatesIdReceiptRouteImport } from './routes/api/v1/candidates/$id/receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CandidatesRoute = ApiV1CandidatesRouteImport.update({
  id: '/api/v1/candidates',
  path: '/api/v1/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RepositoriesRoute = ApiV1RepositoriesRouteImport.update({
  id: '/api/v1/repositories',
  path: '/api/v1/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VerifierJobsRoute = ApiV1VerifierJobsRouteImport.update({
  id: '/api/v1/verifier-jobs',
  path: '/api/v1/verifier-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CandidatesIdRoute = ApiV1CandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1CandidatesRoute,
} as any)
const ApiV1CandidatesIdEvidenceRoute =
  ApiV1CandidatesIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => ApiV1CandidatesIdRoute,
  } as any)
const ApiV1CandidatesIdReceiptRoute =
  ApiV1CandidatesIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => ApiV1CandidatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/candidates': typeof ApiV1CandidatesRouteWithChildren
  '/api/v1/repositories': typeof ApiV1RepositoriesRoute
  '/api/v1/verifier-jobs': typeof ApiV1VerifierJobsRoute
  '/api/v1/candidates/$id': typeof ApiV1CandidatesIdRouteWithChildren
  '/api/v1/candidates/$id/evidence': typeof ApiV1CandidatesIdEvidenceRoute
  '/api/v1/candidates/$id/receipt': typeof ApiV1CandidatesIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/candidates': typeof ApiV1CandidatesRouteWithChildren
  '/api/v1/repositories': typeof ApiV1RepositoriesRoute
  '/api/v1/verifier-jobs': typeof ApiV1VerifierJobsRoute
  '/api/v1/candidates/$id': typeof ApiV1CandidatesIdRouteWithChildren
  '/api/v1/candidates/$id/evidence': typeof ApiV1CandidatesIdEvidenceRoute
  '/api/v1/candidates/$id/receipt': typeof ApiV1CandidatesIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/candidates': typeof ApiV1CandidatesRouteWithChildren
  '/api/v1/repositories': typeof ApiV1RepositoriesRoute
  '/api/v1/verifier-jobs': typeof ApiV1VerifierJobsRoute
  '/api/v1/candidates/$id': typeof ApiV1CandidatesIdRouteWithChildren
  '/api/v1/candidates/$id/evidence': typeof ApiV1CandidatesIdEvidenceRoute
  '/api/v1/candidates/$id/receipt': typeof ApiV1CandidatesIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/reset-password'
    | '/verify'
    | '/workspace'
    | '/api/health'
    | '/api/auth/$'
    | '/api/v1/candidates'
    | '/api/v1/repositories'
    | '/api/v1/verifier-jobs'
    | '/api/v1/candidates/$id'
    | '/api/v1/candidates/$id/evidence'
    | '/api/v1/candidates/$id/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/reset-password'
    | '/verify'
    | '/workspace'
    | '/api/health'
    | '/api/auth/$'
    | '/api/v1/candidates'
    | '/api/v1/repositories'
    | '/api/v1/verifier-jobs'
    | '/api/v1/candidates/$id'
    | '/api/v1/candidates/$id/evidence'
    | '/api/v1/candidates/$id/receipt'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/reset-password'
    | '/verify'
    | '/workspace'
    | '/api/health'
    | '/api/auth/$'
    | '/api/v1/candidates'
    | '/api/v1/repositories'
    | '/api/v1/verifier-jobs'
    | '/api/v1/candidates/$id'
    | '/api/v1/candidates/$id/evidence'
    | '/api/v1/candidates/$id/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  GatesRoute: typeof GatesRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1CandidatesRoute: typeof ApiV1CandidatesRouteWithChildren
  ApiV1RepositoriesRoute: typeof ApiV1RepositoriesRoute
  ApiV1VerifierJobsRoute: typeof ApiV1VerifierJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/candidates': {
      id: '/api/v1/candidates'
      path: '/api/v1/candidates'
      fullPath: '/api/v1/candidates'
      preLoaderRoute: typeof ApiV1CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/repositories': {
      id: '/api/v1/repositories'
      path: '/api/v1/repositories'
      fullPath: '/api/v1/repositories'
      preLoaderRoute: typeof ApiV1RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/verifier-jobs': {
      id: '/api/v1/verifier-jobs'
      path: '/api/v1/verifier-jobs'
      fullPath: '/api/v1/verifier-jobs'
      preLoaderRoute: typeof ApiV1VerifierJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/candidates/$id': {
      id: '/api/v1/candidates/$id'
      path: '/$id'
      fullPath: '/api/v1/candidates/$id'
      preLoaderRoute: typeof ApiV1CandidatesIdRouteImport
      parentRoute: typeof ApiV1CandidatesRoute
    }
    '/api/v1/candidates/$id/evidence': {
      id: '/api/v1/candidates/$id/evidence'
      path: '/evidence'
      fullPath: '/api/v1/candidates/$id/evidence'
      preLoaderRoute: typeof ApiV1CandidatesIdEvidenceRouteImport
      parentRoute: typeof ApiV1CandidatesIdRoute
    }
    '/api/v1/candidates/$id/receipt': {
      id: '/api/v1/candidates/$id/receipt'
      path: '/receipt'
      fullPath: '/api/v1/candidates/$id/receipt'
      preLoaderRoute: typeof ApiV1CandidatesIdReceiptRouteImport
      parentRoute: typeof ApiV1CandidatesIdRoute
    }
  }
}

interface ApiV1CandidatesIdRouteChildren {
  ApiV1CandidatesIdEvidenceRoute: typeof ApiV1CandidatesIdEvidenceRoute
  ApiV1CandidatesIdReceiptRoute: typeof ApiV1CandidatesIdReceiptRoute
}

const ApiV1CandidatesIdRouteChildren: ApiV1CandidatesIdRouteChildren = {
  ApiV1CandidatesIdEvidenceRoute: ApiV1CandidatesIdEvidenceRoute,
  ApiV1CandidatesIdReceiptRoute: ApiV1CandidatesIdReceiptRoute,
}

const ApiV1CandidatesIdRouteWithChildren =
  ApiV1CandidatesIdRoute._addFileChildren(ApiV1CandidatesIdRouteChildren)

interface ApiV1CandidatesRouteChildren {
  ApiV1CandidatesIdRoute: typeof ApiV1CandidatesIdRouteWithChildren
}

const ApiV1CandidatesRouteChildren: ApiV1CandidatesRouteChildren = {
  ApiV1CandidatesIdRoute: ApiV1CandidatesIdRouteWithChildren,
}

const ApiV1CandidatesRouteWithChildren = ApiV1CandidatesRoute._addFileChildren(
  ApiV1CandidatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  GatesRoute: GatesRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ReceiptsRoute: ReceiptsRoute,
  RepositoriesRoute: RepositoriesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1CandidatesRoute: ApiV1CandidatesRouteWithChildren,
  ApiV1RepositoriesRoute: ApiV1RepositoriesRoute,
  ApiV1VerifierJobsRoute: ApiV1VerifierJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
